server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/enote?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password: 123456

  mail:
    host: smtp.163.com
    username: sherly_cs_sh@163.com
    password: INVYADLXFZRQSZAT
    default-encoding: UTF-8
    properties:
      from: sherly_cs_sh@163.com
      mail:
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
#        debug: true

logging:
  level:
    org.springframework.security: DEBUG
